### ISSUE TITLE
Simplfy angular links

### ISSUE THREAD

**Issue by Faisal-Manzer** [Faisal-Manzer/Productive-Summer#27]
Currently [angular](https://github.com/Faisal-Manzer/Productive-Summer#angular) has links to more than 8 tutorials. Shorten them to 2-3 links only. Or break them into sections as [here](https://github.com/Faisal-Manzer/Productive-Summer#react).

@saideepd

**Comment by saideepd** [comment]
Working on it. Will soon make a PR 👍

**Comment by LearnVidFM** [comment]
Thanks @saideepd
